PORT=
MONGO_URL=

HASH_ROUNDS=

FRONT_URL=

JWT_ACCESS_SECRET=
JWT_ACCESS_EXPIRES_IN=
JWT_REFRESH_SECRET=
JWT_REFRESH_EXPIRES_IN=

JWT_ACTION_FORGOT_SECRET=
JWT_ACTION_FORGOT_EXPIRES=
JWT_ACTION_VERIFY_SECRET=
JWT_ACTION_VERIFY_EXPIRES=

SENDGRID_API_KEY=
SENDGRID_FROM_EMAIL=